---
- name: Create the .docker directory if it doesn't exist
  ansible.builtin.file:
    path: /etc/skel/.docker
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy the Docker container proxy configuration
  ansible.builtin.template:
    src: docker-config.json.j2
    dest: /etc/skel/.docker/config.json
    owner: root
    group: root
    mode: 0644
    force: true
