docker_compose_v1_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_v1_release }}/docker-compose-Linux-x86_64"
docker_compose_v1_digest_url: "{{ docker_compose_v1_url }}.sha256"

docker_compose_v2_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_v2_release }}/docker-compose-linux-x86_64"
docker_compose_v2_digest_url: "{{ docker_compose_v2_url }}.sha256"

# The cli-plugins directory can be discovered with `dpkg -L docker-ce-cli | grep cli-plugins`
docker_cli_plugins_dir: /usr/libexec/docker/cli-plugins
