- name: build svc-wss-headers middleware
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_download_kubeconf_path }}{{ rke2_download_kubeconf_file_name }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: svc-wss-headers
        namespace: default
      spec:
        headers:
          customRequestHeaders:
            X-Forwarded-Proto: "https"

- name: strip prefix longhorn middleware
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_download_kubeconf_path }}{{ rke2_download_kubeconf_file_name }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: strip-prefix-longhorn
        namespace: default
      spec:
        stripPrefix:
          prefixes:
            - /longhorn
          forceSlash: false

- name: create longhorn auth secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_download_kubeconf_path }}{{ rke2_download_kubeconf_file_name }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: longhorn-auth-secret
        namespace: default
      data:
        users: "{{ longhorn_admin_secret }}"

- name: basic auth longhorn middleware
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_download_kubeconf_path }}{{ rke2_download_kubeconf_file_name }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: Middleware
      metadata:
        name: auth-longhorn
        namespace: default
      spec:
        basicAuth:
          secret: longhorn-auth-secret

- name: build ingress route
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_download_kubeconf_path }}{{ rke2_download_kubeconf_file_name }}"
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: longhorn
        namespace: default
      spec:
        entrypoints:
          - web
        routes:
          - match: PathPrefix(`/longhorn`)
            kind: Rule
            middlewares:
              - name: svc-wss-headers
                namespace: default
              - name: strip-prefix-longhorn
                namespace: default
              - name: auth-longhorn
                namespace: default
            services:
              - name: longhorn-frontend
                namespace: longhorn-system
                port: 80
