- name: create /local directory
  ansible.builtin.file:
    path: /local
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true
  tags:
    - mount_local

- name: partition all defined drives
  community.general.parted:
    device: "{{ k8s_setup_longhorn_item.device }}"
    number: "{{ k8s_setup_longhorn_item.number }}"
    label: "{{ k8s_setup_longhorn_item.label }}"
    state: present
  become: true
  loop: "{{ longhorn_nodes_additional_storage_layout }}"
  loop_control:
    loop_var: k8s_setup_longhorn_item
  tags:
    - mount_local

- name: format all defined drives
  community.general.filesystem:
    fstype: ext4
    dev: "{{ k8s_setup_longhorn_item.device }}{{ k8s_setup_longhorn_item.number }}"
  become: true
  loop: "{{ longhorn_nodes_additional_storage_layout }}"
  loop_control:
    loop_var: k8s_setup_longhorn_item

- name: mount drives to /local/
  mount:
    path: "/local/{{ k8s_setup_longhorn_item.name }}"
    src: "{{ k8s_setup_longhorn_item.device }}{{ k8s_setup_longhorn_item.number }}"
    fstype: ext4
    state: mounted
  become: true
  loop: "{{ longhorn_nodes_additional_storage_layout }}"
  loop_control:
    loop_var: k8s_setup_longhorn_item
  tags:
    - mount_local
