---
- name: Install prerequisites
  ansible.builtin.apt:
    name: ca-certificates
    state: present
  tags:
    - seafile

- name: Download the signing key
  ansible.builtin.get_url:
    url: https://linux-clients.seafile.com/seafile.asc
    dest: "{{ seafile_key_path }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - seafile

- name: Add the repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ seafile_key_path }}] https://linux-clients.seafile.com/seafile-deb/{{ ansible_distribution_release }}/ stable main"
    state: present
  tags:
    - seafile

- name: Install the command-line client
  ansible.builtin.apt:
    name: seafile-cli
    update_cache: true
    state: present
  tags:
    - seafile
