---
- name: Set up proxy variables in Bash
  ansible.builtin.template:
    src: "{{ proxy_env_filename }}.j2"
    dest: "/etc/profile.d/{{ proxy_env_filename }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - proxy

- name: gather information about installed packages
  ansible.builtin.package_facts:
    manager: apt

- name: Set up proxy variables in zsh
  ansible.builtin.blockinfile:
    path: /etc/zsh/zprofile
    block: "{{ lookup('template', 'zprofile.j2') }}"
    owner: root
    group: root
    create: false
    state: present
  when: "'zsh' in ansible_facts.packages"
  tags:
    - proxy
