---
- name: create prometheus additional config resource
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ rke2_kubeconf_host_path }}{{ rke2_download_kubeconf_file_name }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: additional-scrape-configs
        namespace: monitoring
      data:
        config: "{{ scrape_config | string | b64encode }}"
  register: scrape_config_result
