- name: loop through the network interfaces to find the current main one
  ansible.builtin.set_fact:
    main_interface: "{{ set_default_gw_item }}"
  loop: "{{ ansible_interfaces }}"
  loop_control:
    loop_var: set_default_gw_item
  when:
    - lookup('vars', 'ansible_' + set_default_gw_item)['active']
    - '"flannel" not in set_default_gw_item'
    - '"cali" not in set_default_gw_item'
    - lookup('vars', 'ansible_' + set_default_gw_item)['ipv4']['network'] == main_network

- name: retrieve cloud-init information
  community.general.cloud_init_data_facts:
  register: cloud_init_res
  become: true

- name: write netplan default gw config
  ansible.builtin.template:
    src: 60-default-gw.yml.j2
    dest: /etc/netplan/60-default-gw.yaml
    owner: root
    group: root
    mode: 0644
  when: cloud_init_res['cloud_init_data_facts']['status']['v1']['stage'] is defined
  become: true
  notify: apply netplan config
