---
- name: Install podman
  ansible.builtin.apt:
    name: podman
    state: present
  tags: podman

- name: Prepare the parent directory for rootless container storage
  ansible.builtin.file:
    path: "{{ container_storage_root }}"
    state: directory
    mode: 0777
  tags: podman
