- name: Install the container runtime
  ansible.builtin.include_role:
    name: nvidia.nvidia_docker

- name: Flush handlers before testing
  ansible.builtin.meta: flush_handlers

- name: Test the container runtime
  community.docker.docker_container:
    name: "nvidia-smi"
    image: "{{ cuda_nvidia_image }}"
    auto_remove: true
    cleanup: true
    command: "nvidia-smi"
    state: started
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - - gpu
            - utility
