
- name: install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
  become: true

- name: Create directory for keepalived
  ansible.builtin.file:
    path: /etc/keepalived
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Create the keepalived_script user
  ansible.builtin.user:
    name: keepalived_script
    create_home: false
    system: true
    state: present
  become: true

- name: Create Kubernetes API health check script
  ansible.builtin.template:
    src: templates/check_apiserver.sh.j2
    dest: /etc/keepalived/check_apiserver.sh
    owner: root
    group: root
    mode: 0755
  become: true
  notify: restart keepalived

- name: Create keepalived config file
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart keepalived

- name: Enable keepalived and make sure it is not masked
  ansible.builtin.systemd:
    name: keepalived
    enabled: yes
    masked: no
  become: true
  notify: restart keepalived

- name: Flush handlers
  meta: flush_handlers